name: hydro_control
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bluetooth_serial: ^0.4.0
  flutter_blue: ^0.8.0
  permission_handler: ^11.0.0
  open_settings: ^2.0.2
  flutter_web_bluetooth: ^0.2.1
  flutter_localization: ^0.1.13
  

flutter_localizations:
  sdk: flutter
  package: flutter_localizations
  options:
    languages:
      - es
      - en
      - pt
      - de
      - zh
      - ja

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true

  main_locale: es

  class_name: S
